// Regenerates src/lib/api/schema.ts from the FastAPI OpenAPI document.
//
//   npm run generate:api
//
// CI fails when the committed schema differs from a fresh export, so run this
// after changing any API route or schema and commit the result.
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = resolve(webRoot, "..");

function findPython() {
  if (process.env.PYTHON) return process.env.PYTHON;
  for (const candidate of [".venv/bin/python", "api/.venv/bin/python"]) {
    const path = resolve(repoRoot, candidate);
    if (existsSync(path)) return path;
  }
  return "python3";
}

const document = execFileSync(findPython(), ["api/scripts/export_openapi.py"], {
  cwd: repoRoot,
  encoding: "utf8",
});
const nodes = await openapiTS(JSON.parse(document));

await writeFile(
  resolve(webRoot, "src/lib/api/schema.ts"),
  `// Generated by \`npm run generate:api\` from the FastAPI OpenAPI document. Do not edit.\n${astToString(nodes)}`,
);
